#!/usr/bin/env python3
"""
Cor Sono — train_model.py
Train the int8 1D-CNN cardiopulmonary sound classifier.

Trains on:
    - PASCAL heart sound challenge dataset
    - CirCori DigiScope dataset
    - ICBHI lung sound database

Outputs:
    - cor_sono_cnn_int8.tflite (quantized int8 model)
    - model_data.h (C array for ESP32-S3 firmware)

Usage:
    python3 train_model.py --pascal /data/pascal --circori /data/circori --icbhi /data/icbhi

Requires: tensorflow>=2.13, numpy, scipy, librosa
"""
import argparse
import os
import numpy as np

try:
    import tensorflow as tf
    from tensorflow import keras
    from tensorflow.keras import layers
except ImportError:
    print("Install: pip install tensorflow librosa numpy scipy")
    exit(1)

try:
    import librosa
except ImportError:
    print("Install: pip install librosa")
    exit(1)

SAMPLE_RATE = 4000
MEL_BINS = 32
MEL_FRAMES = 40
N_CLASSES = 8
BATCH = 32
EPOCHS = 50

CLASS_NAMES = [
    "normal", "s3", "s4", "sys_murmur",
    "dia_murmur", "crackles", "wheeze", "rub"
]


def compute_mel(audio, sr=SAMPLE_RATE):
    """Compute mel-spectrogram matching firmware preprocessing."""
    mel = librosa.feature.melspectrogram(
        y=audio, sr=sr, n_fft=256, hop_length=40,
        n_mels=MEL_BINS, fmin=20, fmax=2000
    )
    mel_db = librosa.power_to_db(mel + 1e-10, ref=np.max)
    # Normalize to 0-1
    mel_db = (mel_db - mel_db.min()) / (mel_db.max() - mel_db.min() + 1e-10)
    # Pad/trim to MEL_FRAMES
    if mel_db.shape[1] < MEL_FRAMES:
        mel_db = np.pad(mel_db, ((0, 0), (0, MEL_FRAMES - mel_db.shape[1])))
    else:
        mel_db = mel_db[:, :MEL_FRAMES]
    return mel_db


def load_dataset(path, label_map):
    """Load audio files and compute mel-spectrograms."""
    X, y = [], []
    for label_name, label_id in label_map.items():
        dir_path = os.path.join(path, label_name)
        if not os.path.isdir(dir_path):
            continue
        for fname in os.listdir(dir_path):
            if not fname.endswith((".wav", ".mp3")):
                continue
            fpath = os.path.join(dir_path, fname)
            audio, _ = librosa.load(fpath, sr=SAMPLE_RATE, mono=True)
            # Take 1-second segments
            seg_len = SAMPLE_RATE
            for start in range(0, len(audio) - seg_len, seg_len // 2):
                seg = audio[start:start + seg_len]
                mel = compute_mel(seg)
                X.append(mel)
                y.append(label_id)
    return np.array(X), np.array(y)


def build_model():
    """Build 1D-CNN matching firmware architecture."""
    model = keras.Sequential([
        layers.Input(shape=(MEL_BINS, MEL_FRAMES, 1)),
        layers.Conv2D(8, (3, 3), activation="relu", padding="same"),
        layers.MaxPooling2D((2, 1)),
        layers.Conv2D(16, (3, 3), activation="relu", padding="same"),
        layers.MaxPooling2D((2, 1)),
        layers.Conv2D(32, (3, 3), activation="relu", padding="same"),
        layers.MaxPooling2D((2, 1)),
        layers.Conv2D(32, (3, 3), activation="relu", padding="same"),
        layers.GlobalAveragePooling2D(),
        layers.Dense(16, activation="relu"),
        layers.Dense(N_CLASSES, activation="softmax"),
    ])
    model.compile(
        optimizer="adam",
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"],
    )
    return model


def quantize_model(model, out_tflite, out_header):
    """Full integer post-training quantization."""
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.int8
    converter.inference_output_type = tf.int8

    # Representative dataset for quantization
    def rep_data():
        for i in range(100):
            yield [np.random.randn(1, MEL_BINS, MEL_FRAMES, 1).astype(np.float32)]

    converter.representative_dataset = rep_data
    tflite_model = converter.convert()

    with open(out_tflite, "wb") as f:
        f.write(tflite_model)
    print(f"Saved quantized model: {out_tflite} ({len(tflite_model)} bytes)")

    # Convert to C header
    with open(out_header, "w") as f:
        f.write("/* Auto-generated by train_model.py */\n")
        f.write("#pragma once\n#include <stdint.h>\n\n")
        f.write("static const unsigned char g_model_data[] = {\n")
        for i, b in enumerate(tflite_model):
            if i % 16 == 0:
                f.write("  ")
            f.write(f"0x{b:02x},")
            if i % 16 == 15:
                f.write("\n")
            else:
                f.write(" ")
        f.write("\n};\n")
        f.write(f"static const size_t g_model_data_len = {len(tflite_model)};\n")
    print(f"Saved C header: {out_header}")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--pascal", default=None, help="PASCAL dataset path")
    parser.add_argument("--circori", default=None, help="CirCori dataset path")
    parser.add_argument("--icbhi", default=None, help="ICBHI dataset path")
    parser.add_argument("--epochs", type=int, default=EPOCHS)
    args = parser.parse_args()

    label_map = {name: i for i, name in enumerate(CLASS_NAMES)}

    X_all, y_all = [], []
    for ds_path in [args.pascal, args.circori, args.icbhi]:
        if ds_path and os.path.isdir(ds_path):
            print(f"Loading {ds_path}...")
            X, y = load_dataset(ds_path, label_map)
            X_all.append(X)
            y_all.append(y)
            print(f"  {len(X)} samples")

    if not X_all:
        print("No data found. Using synthetic data for demo.")
        X_all = [np.random.randn(200, MEL_BINS, MEL_FRAMES).astype(np.float32)]
        y_all = [np.random.randint(0, N_CLASSES, 200)]

    X = np.concatenate(X_all)
    y = np.concatenate(y_all)
    X = X[..., np.newaxis]  # add channel dim
    print(f"Total: {len(X)} samples, {N_CLASSES} classes")

    model = build_model()
    model.summary()

    model.fit(X, y, batch_size=BATCH, epochs=args.epochs,
              validation_split=0.2, verbose=1)

    quantize_model(model, "cor_sono_cnn_int8.tflite", "model_data.h")
    print("Done. Copy model_data.h to firmware/main/model_data.h")


if __name__ == "__main__":
    main()