#!/usr/bin/env python3
"""
Levia Forge — 3D Acoustic Field Visualizer

Simulates and visualizes the acoustic pressure field generated by the
72-transducer phased array for a given focal point. Useful for
verifying phase patterns before loading them onto the device.

Usage:
    python3 phase_visualizer.py [--x X] [--y Y] [--z Z] [--pattern PATTERN]

Requires:
    pip install numpy matplotlib
"""

import argparse
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import Normalize

# Physical constants
CARRIER_FREQ = 40000       # Hz
SPEED_OF_SOUND = 343.0     # m/s
WAVELENGTH = SPEED_OF_SOUND / CARRIER_FREQ  # ~8.575 mm

# Array geometry
NUM_TOP = 36
NUM_BOTTOM = 36
NUM_TOTAL = NUM_TOP + NUM_BOTTOM
ARRAY_COLS = 6
ARRAY_ROWS = 6
ELEMENT_SPACING = 10.0     # mm
CURVATURE_RADIUS = 40.0    # mm
TOP_Z = 35.0               # mm
BOTTOM_Z = -35.0           # mm


def compute_transducer_positions():
    """Compute 3D positions of all 72 transducers."""
    positions = []
    half = (ARRAY_COLS - 1) / 2.0

    # Top array (indices 0-35)
    for row in range(ARRAY_ROWS):
        for col in range(ARRAY_COLS):
            x = (col - half) * ELEMENT_SPACING
            y = (row - half) * ELEMENT_SPACING
            r_sq = x**2 + y**2
            z_offset = 0.0
            if r_sq < CURVATURE_RADIUS**2:
                z_offset = CURVATURE_RADIUS - np.sqrt(
                    CURVATURE_RADIUS**2 - r_sq)
            positions.append((x, y, TOP_Z + z_offset))

    # Bottom array (indices 36-71)
    for row in range(ARRAY_ROWS):
        for col in range(ARRAY_COLS):
            x = (col - half) * ELEMENT_SPACING
            y = (row - half) * ELEMENT_SPACING
            r_sq = x**2 + y**2
            z_offset = 0.0
            if r_sq < CURVATURE_RADIUS**2:
                z_offset = CURVATURE_RADIUS - np.sqrt(
                    CURVATURE_RADIUS**2 - r_sq)
            positions.append((x, y, BOTTOM_Z - z_offset))

    return np.array(positions)


def compute_pressure_field(positions, focal_point, grid_x, grid_z,
                            pattern='point', y_plane=0.0):
    """
    Compute the acoustic pressure field in the X-Z plane at y=y_plane.

    p(x, z) = Σ_i A_i * exp(j * k * |t_i - (x, y, z)| + j * φ_i)

    where φ_i is the phase delay for focusing at focal_point.
    """
    k = 2 * np.pi / WAVELENGTH  # wavenumber (rad/mm)

    # Compute phases for each transducer
    phases = np.zeros(NUM_TOTAL)
    fx, fy, fz = focal_point

    for i in range(NUM_TOTAL):
        tx, ty, tz = positions[i]
        dist = np.sqrt((tx - fx)**2 + (ty - fy)**2 + (tz - fz)**2)

        if pattern == 'point':
            phases[i] = k * dist
        elif pattern == 'vortex':
            theta = np.arctan2(ty - fy, tx - fx)
            phases[i] = k * dist + 1.0 * theta  # ℓ=1
        elif pattern == 'twin':
            # Alternate between two foci
            if i % 2 == 0:
                dist = np.sqrt((tx - fx + 4)**2 + (ty - fy)**2 + (tz - fz)**2)
            else:
                dist = np.sqrt((tx - fx - 4)**2 + (ty - fy)**2 + (tz - fz)**2)
            phases[i] = k * dist
        elif pattern == 'bending':
            phases[i] = k * dist + 0.02 * tx  # linear gradient
        else:
            phases[i] = k * dist

    # Compute pressure field on the grid
    # p(x, z) = Σ_i exp(j*k*r_i + j*φ_i) / r_i
    # (simplified: ignore 1/r attenuation, use unit amplitude)
    X, Z = np.meshgrid(grid_x, grid_z)
    pressure = np.zeros_like(X, dtype=complex)

    for i in range(NUM_TOTAL):
        tx, ty, tz = positions[i]
        dx = X - tx
        dy = y_plane - ty
        dz = Z - tz
        dist = np.sqrt(dx**2 + dy**2 + dz**2)
        # Avoid division by zero
        dist = np.maximum(dist, 1.0)
        pressure += np.exp(1j * (k * dist + phases[i])) / np.sqrt(dist)

    return np.abs(pressure)


def plot_field(pressure, grid_x, grid_z, focal_point, pattern):
    """Plot the pressure field as a heatmap."""
    fig, ax = plt.subplots(1, 1, figsize=(10, 8))

    # Plot magnitude
    im = ax.pcolormesh(grid_x, grid_z, pressure,
                       cmap='hot', shading='auto',
                       norm=Normalize(vmin=0, vmax=np.max(pressure)))

    # Mark focal point
    ax.plot(focal_point[0], focal_point[1], 'c+', markersize=15,
            markeredgewidth=2, label='Focal point')

    # Mark transducer positions (projected onto X-Z plane)
    positions = compute_transducer_positions()
    for i in range(NUM_TOTAL):
        ax.plot(positions[i, 0], positions[i, 2], 'b^',
                markersize=4, alpha=0.5)

    ax.set_xlabel('X (mm)')
    ax.set_ylabel('Z (mm)')
    ax.set_title(f'Levia Forge — Acoustic Pressure Field\n'
                 f'Pattern: {pattern}, Focal: {focal_point}')
    ax.set_xlim(-40, 40)
    ax.set_ylim(-45, 45)
    ax.legend()
    fig.colorbar(im, ax=ax, label='Pressure (a.u.)')
    ax.set_aspect('equal')

    plt.tight_layout()
    plt.show()


def main():
    parser = argparse.ArgumentParser(
        description='Levia Forge — Acoustic Field Visualizer')
    parser.add_argument('--x', type=float, default=0.0,
                        help='Focal point X (mm)')
    parser.add_argument('--y', type=float, default=0.0,
                        help='Focal point Y (mm)')
    parser.add_argument('--z', type=float, default=10.0,
                        help='Focal point Z (mm)')
    parser.add_argument('--pattern', type=str, default='point',
                        choices=['point', 'twin', 'vortex', 'bending'],
                        help='Phase pattern')
    args = parser.parse_args()

    # Compute transducer positions
    positions = compute_transducer_positions()

    # Create evaluation grid (X-Z plane at y=0)
    grid_x = np.linspace(-40, 40, 200)
    grid_z = np.linspace(-45, 45, 200)

    # Compute pressure field
    focal = (args.x, args.y, args.z)
    pressure = compute_pressure_field(
        positions, focal, grid_x, grid_z,
        pattern=args.pattern, y_plane=0.0)

    # Plot
    plot_field(pressure, grid_x, grid_z, (args.x, args.z), args.pattern)


if __name__ == "__main__":
    main()