/*
 * model_weights.h — Quantized int8 CNN weights (placeholder)
 *
 * These are placeholder weights. Real weights are generated by
 * scripts/train_model.py, which trains a 1D-CNN on wingbeat audio data,
 * quantizes to int8, and exports this C header.
 *
 * Architecture:
 *   Conv1: in_ch=2, out_ch=8, kernel=5 → 8×2×5 = 80 weights, 8 biases
 *   Conv2: in_ch=8, out_ch=16, kernel=5 → 16×8×5 = 640 weights, 16 biases
 *   Conv3: in_ch=16, out_ch=32, kernel=5 → 32×16×5 = 2560 weights, 32 biases
 *   Dense: in=32, out=12 → 32×12 = 384 weights, 12 biases
 *   Total: 3664 int8 weights + 68 int32 biases = ~8 KB (with int8 weights + int32 biases)
 *
 * Copyright (c) 2026 SoC Device Inventions. MIT License.
 */

#ifndef ECHO_TRAP_MODEL_WEIGHTS_H
#define ECHO_TRAP_MODEL_WEIGHTS_H

#include <stdint.h>

/* Conv1: [8 out × 2 in × 5 kernel] = 80 int8 weights */
static const int8_t conv1_w[80] = {
    /* Placeholder zeros — replace with trained weights */
    0, 0, 0, 0, 0,  0, 0, 0, 0, 0,
    0, 0, 0, 0, 0,  0, 0, 0, 0, 0,
    0, 0, 0, 0, 0,  0, 0, 0, 0, 0,
    0, 0, 0, 0, 0,  0, 0, 0, 0, 0,
    0, 0, 0, 0, 0,  0, 0, 0, 0, 0,
    0, 0, 0, 0, 0,  0, 0, 0, 0, 0,
    0, 0, 0, 0, 0,  0, 0, 0, 0, 0,
    0, 0, 0, 0, 0,  0, 0, 0, 0, 0,
};
static const int32_t conv1_b[8] = { 0, 0, 0, 0, 0, 0, 0, 0 };

/* Conv2: [16 out × 8 in × 5 kernel] = 640 int8 weights */
static const int8_t conv2_w[640] = {
    /* Placeholder — 640 zeros */
    0,
};
static const int32_t conv2_b[16] = {
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
};

/* Conv3: [32 out × 16 in × 5 kernel] = 2560 int8 weights */
static const int8_t conv3_w[2560] = {
    /* Placeholder — 2560 zeros */
    0,
};
static const int32_t conv3_b[32] = {
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
};

/* Dense: [12 out × 32 in] = 384 int8 weights */
static const int8_t dense_w[384] = {
    /* Placeholder — 384 zeros */
    0,
};
static const int32_t dense_b[12] = {
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
};

#endif /* ECHO_TRAP_MODEL_WEIGHTS_H */