#!/usr/bin/env python3
"""
train_cnn.py — Train the int8 1D-CNN spike classifier for Phyto Pulse.

Loads labeled spike data (CSV with waveform windows + class labels),
trains a small 1D-CNN in TensorFlow/Keras, quantizes to int8, and
exports weights as a C header file (cnn_weights.h) for the STM32G474.

Usage:
    python3 train_cnn.py --data training_data.csv --output ../firmware/Core/Inc/cnn_weights.h

Training data CSV format:
    Each row: 64 comma-separated sample values followed by class label (AP/VP/ART)
    Example: 0.023,0.045,...,-0.012,AP

Requirements:
    pip install tensorflow numpy
"""

import argparse
import csv
import numpy as np
from pathlib import Path

try:
    import tensorflow as tf
    from tensorflow import keras
    HAS_TF = True
except ImportError:
    HAS_TF = False


CLASS_MAP = {'AP': 0, 'VP': 1, 'ART': 2}
INV_CLASS_MAP = {0: 'AP', 1: 'VP', 2: 'ART'}


def load_data(filepath):
    """Load training data from CSV: 64 values + label per row."""
    X, y = [], []
    with open(filepath, 'r') as f:
        reader = csv.reader(f)
        for row in reader:
            if len(row) < 65:
                continue
            features = [float(v) for v in row[:64]]
            label = row[64].strip()
            if label in CLASS_MAP:
                X.append(features)
                y.append(CLASS_MAP[label])
    X = np.array(X, dtype=np.float32).reshape(-1, 64, 1)
    y = np.array(y, dtype=np.int32)
    return X, y


def build_model():
    """Build the 1D-CNN: Conv1(8,k=7,s=2) → Conv2(16,k=5,s=1) → Pool → Conv3(16,k=3) → Dense(32) → Dense(3)"""
    model = keras.Sequential([
        keras.layers.InputLayer(input_shape=(64, 1)),
        keras.layers.Conv1D(8, kernel_size=7, strides=2, activation='relu',
                            name='conv1'),
        keras.layers.Conv1D(16, kernel_size=5, strides=1, activation='relu',
                            name='conv2'),
        keras.layers.MaxPooling1D(pool_size=2, name='pool'),
        keras.layers.Conv1D(16, kernel_size=3, strides=1, activation='relu',
                            name='conv3'),
        keras.layers.Flatten(name='flatten'),
        keras.layers.Dense(32, activation='relu', name='dense1'),
        keras.layers.Dense(3, activation='softmax', name='dense2'),
    ])
    model.compile(optimizer='adam', loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])
    return model


def quantize_model(model, X_train):
    """Quantize model to int8 using post-training quantization."""
    def representative_data():
        for i in range(min(100, len(X_train))):
            yield [X_train[i:i+1].astype(np.float32)]

    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = representative_data
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.int8
    converter.inference_output_type = tf.int8

    quantized = converter.convert()
    return quantized


def export_weights_c_header(model, output_path):
    """Export model weights as a C header file for CMSIS-NN."""
    layers = ['conv1', 'conv2', 'conv3', 'dense1', 'dense2']

    with open(output_path, 'w') as f:
        f.write("/* Auto-generated by train_cnn.py — do not edit manually */\n")
        f.write("#ifndef CNN_WEIGHTS_GEN_H\n#define CNN_WEIGHTS_GEN_H\n\n")
        f.write("#include <stdint.h>\n\n")

        for layer_name in layers:
            layer = model.get_layer(layer_name)
            w = layer.get_weights()[0]
            b = layer.get_weights()[1]

            # Quantize weights to int8 (simple: scale to ±127)
            w_max = np.max(np.abs(w))
            w_scale = 127.0 / w_max if w_max > 0 else 1.0
            w_int8 = np.clip(w * w_scale, -128, 127).astype(np.int8)

            f.write(f"/* {layer_name}: weights {w.shape}, bias {b.shape} */\n")
            f.write(f"static const int8_t {layer_name}_w[{w_int8.size}] = {{\n")
            f.write("    " + ", ".join(str(int(x)) for x in w_int8.flatten()))
            f.write("\n};\n\n")

            f.write(f"static const int32_t {layer_name}_b[{len(b)}] = {{\n")
            f.write("    " + ", ".join(str(int(x * w_scale * 256)) for x in b))
            f.write("\n};\n\n")

        f.write(f"/* Input scale: {1.0/64.0} (voltage_mV to int8) */\n")
        f.write(f"#define INPUT_SCALE_GEN 0.015625f\n\n")
        f.write("#endif /* CNN_WEIGHTS_GEN_H */\n")

    print(f"Weights exported to {output_path}")


def main():
    parser = argparse.ArgumentParser(description='Train Phyto Pulse spike classifier')
    parser.add_argument('--data', required=True, help='Training data CSV')
    parser.add_argument('--output', default='cnn_weights.h', help='Output C header')
    parser.add_argument('--epochs', type=int, default=50, help='Training epochs')
    args = parser.parse_args()

    if not HAS_TF:
        print("TensorFlow not installed. Install with: pip install tensorflow")
        print("Generating placeholder weights (all zeros)...")
        # Generate placeholder header
        with open(args.output, 'w') as f:
            f.write("/* Placeholder weights — train with TensorFlow to replace */\n")
            f.write("#ifndef CNN_WEIGHTS_GEN_H\n#define CNN_WEIGHTS_GEN_H\n")
            f.write("#include <stdint.h>\n")
            f.write("/* ... placeholder ... */\n")
            f.write("#endif\n")
        return

    print("Loading training data...")
    X, y = load_data(args.data)
    print(f"  {len(X)} samples, {X.shape}")

    # Split train/test
    n = len(X)
    idx = np.random.permutation(n)
    split = int(0.8 * n)
    X_train, X_test = X[idx[:split]], X[idx[split:]]
    y_train, y_test = y[idx[:split]], y[idx[split:]]

    print("Building model...")
    model = build_model()
    model.summary()

    print(f"Training for {args.epochs} epochs...")
    history = model.fit(X_train, y_train, epochs=args.epochs,
                        validation_data=(X_test, y_test), verbose=1)

    # Evaluate
    loss, acc = model.evaluate(X_test, y_test)
    print(f"Test accuracy: {acc:.3f}")

    # Confusion matrix
    y_pred = np.argmax(model.predict(X_test), axis=1)
    for true_class in range(3):
        mask = y_test == true_class
        pred_dist = np.bincount(y_pred[mask], minlength=3) / mask.sum()
        print(f"  True {INV_CLASS_MAP[true_class]}: "
              f"→ AP={pred_dist[0]:.2f} VP={pred_dist[1]:.2f} ART={pred_dist[2]:.2f}")

    # Export weights as C header
    print("Exporting weights...")
    export_weights_c_header(model, args.output)

    print(f"\nDone! Replace cnn_weights.h in firmware with {args.output}")
    print("Rebuild and flash firmware to use the trained classifier.")


if __name__ == '__main__':
    main()