/* pio_sonic.h — auto-generated PIO header (manually created for reference)
 *
 * In a real build, this is generated by pioasm from pio_sonic.pio.
 */

#ifndef PIO_SONIC_H
#define PIO_SONIC_H

#include "hardware/pio.h"

#define sonic_tx_wrap_target 0u
#define sonic_tx_wrap 8u
#define sonic_tx_T0 0u
#define sonic_tx_T1 1u

#define sonic_rx_wrap_target 0u
#define sonic_rx_wrap 5u
#define sonic_rx_T0 0u
#define sonic_rx_T1 1u

static inline void sonic_tx_program_init(PIO pio, uint sm, uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + sonic_tx_wrap_target, offset + sonic_tx_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    pio_sm_init(pio, sm, offset, &c);
}

static inline void sonic_rx_program_init(PIO pio, uint sm, uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + sonic_rx_wrap_target, offset + sonic_rx_wrap);
    pio_sm_init(pio, sm, offset, &c);
}

/* The PIO program instructions would be compiled by pioasm into a
 * pio_program_t structure. For the reference firmware, we define
 * the program entry points and let the build system handle the
 * actual PIO binary generation.
 *
 * In the real CMake build, the .pio file is processed by pioasm:
 *   pioasm -o c pio_sonic.pio pio_sonic.h
 * which generates the pio_program_t and _get_default_config() functions.
 */

/* Placeholder: in real build, pioasm generates these */
#define sonic_tx_program { sonic_tx_instructions, sonic_tx_wrap_target, sonic_tx_wrap }
#define sonic_rx_program { sonic_rx_instructions, sonic_rx_wrap_target, sonic_rx_wrap }

static inline pio_sm_config sonic_tx_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + sonic_tx_wrap_target, offset + sonic_tx_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}

static inline pio_sm_config sonic_rx_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + sonic_rx_wrap_target, offset + sonic_rx_wrap);
    return c;
}

#endif /* PIO_SONIC_H */